version : '3.7'

services:
  notebook:
    build: ./
    ports:
      - 8888:8888
    volumes:
      - ./src:/home/jovyan/work
    environment:
      - PYTHONPATH=/home/jovyan/work/
      - PASSWORD=rhinos
